### ISSUE TITLE
Master branch has unreleased changes

### ISSUE THREAD

**Issue by noomorph** [benbria/bunyan-debug-stream#11]
Please, publish the new release to NPM registry. 

I assume that something did not work out 8 hours ago with the last commit that added semantic release. If it proves to be a time consuming change, maybe let's do that in a simpler way this week. 

I'm sorry if I remind here the obvious things but it will be easier to track the progress on this.

Many thanks in advance!

**Comment by noomorph** [comment]
I was referring to this specific build:
https://travis-ci.org/benbria/bunyan-debug-stream/jobs/407329371

Looks like it does not have push access to the git.

**Comment by jwalton** [comment]
Sorry; I had to run last night - my daughter is at parkour camp this week, and I had to pick her up on time, because they charge like $15 per 10 minutes I'm late.  :P  So I pushed to Travis and crossed my fingers.  Just sorted it all out.  Everything should be in 1.1.0 now.

**Comment by noomorph** [comment]
You are :crown: , thank you so much!

**Comment by jwalton** [comment]
No problem.  Sorry I didn't fix it last night.  :P

**Comment by noomorph** [comment]
@jwalton, no need to apologize! I'm already enormously happy and grateful that you gave me an opportunity to switch the `bunyan-debug-stream` version in `package.json` from my fork to your mainstream one. Otherwise, I would have been sitting on Plan B, decaffeinating the lib and inserting into the existing codebase, plus making sure all the legal acknowledgments are in place - not fun, I'd say.

You saved me a good couple of hours for sure! 

https://github.com/wix/detox/blob/noomorph/powerlogs/detox/package.json#L42

**Comment by jwalton** [comment]
Haha.  I started decaffeinating this just a couple of weeks ago, actually, but then decided to switch to Winston.  ;)

**Comment by noomorph** [comment]
Good for you :+1: 

I also tried out Winston, but my experience was far from satisfying. The Bunyan's killer feature of easy `.child({ ... })` logger metadata creation was missing, and to my great displeasure, I wasn't so lucky to find or implement a quick workaround.

Did you hit that issue too? Or you don't create child loggers that much?
