### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by mashaalmemon** [benbria/bunyan-debug-stream#12]
Hi There,

Any way to easily specify the date format? Would love to get UTC time with ms if possible and easy.

Thanks.

**Comment by jwalton** [comment]
I just pushed a change that lets you pass in a custom function in the options:

```js
new BunyanDebugStream({
    showDate: (time, entry) => return time.toISOString()
});
```

That should let you use whatever format you want.  If that doesn't fix it for you, please feel free to reopen.  (semantic-release should comment here with the new version number when this change gets published.)
