### ISSUE TITLE
Colored output doesn't work

### ISSUE THREAD

**Issue by DenisIzmaylov** [benbria/bunyan-debug-stream#3]
Somebody else have the same issues?

**Comment by jwalton** [comment]
I use the colored output literally every day.  Do you have a gist or a small project that reproduces your problem?

**Comment by DenisIzmaylov** [comment]
I will try to demonstrate code parts:
```javascript
import DebugStream from 'bunyan-debug-stream';
// ..
const logger = bunyan.createLogger({
  name: 'my-app',
  streams: [{
    stream: new DebugStream({
      basepath: __dirname,
      prefixers: {
        'module': (module, options) => {
          return {
            value: module + (options.entry['method'] ? ' => ' + options.entry['method'] : ''),
            consumed: ['module', 'method']
          };
        }
      }
    }),
    level: 'trace',
    type: 'raw'
  }]
});

**Comment by kingcody** [comment]
@DenisIzmaylov I was having a very similar issue, my problem was that `process.stdout` was not a tty and `colors.js` disables colored output on non-tty by default. If you think this might relate to your issue, check out #5 for my solution.

**Comment by jwalton** [comment]
@DenisIzmaylov try upgrading to v1.0.7 and adding the `forceColor` option.  If this doesn't fix it for you, please feel free to re-open this.

**Comment by DenisIzmaylov** [comment]
Thank you
