### ISSUE TITLE
TypeError in utils.js

### ISSUE THREAD

**Issue by YouriT** [benbria/bunyan-debug-stream#6]
Getting an error with this module on version `1.0.7`
Here it is:

``` bash
TypeError: undefined is not a function
    at ...node_modules/bunyan-debug-stream/lib/utils.js:31:25
```

The error references to the fact that in this file you do a `date.get...` but `date` is an ISOString and not an object.

Thanks for this great work!

**Comment by jwalton** [comment]
Sorry for not replying to this earlier - was on vacation when you raised it, and I missed it.

How are you getting an ISOString out of bunyan?  What version of bunyan are you using?  Easy enough to add a `date = new Date(date)` here if we need to, though.

**Comment by veeramarni** [comment]
I think by adding time variable will fix this issue. 

```
  const bunyanDebugStream = require('bunyan-debug-stream');
  // stream: process.stdout,
  const stream = bunyanDebugStream({
    basepath: __dirname, // this should be the root folder of your project.
    forceColor: true,
  });
  streams = [{
    level: level || 'debug',
    type: 'stream',
    stream,
  }];
}
const logger = bunyan.createLogger({
  name: app,
  time: Date,
  streams
});
```

**Comment by jaulz** [comment]
Same issue here... using `bunyan@^1.8.12`

**Comment by jwalton** [comment]
@benbriadeploy is a robot.  :)  But no problem.

**Comment by jwalton** [comment]
Also, I fixed this by making it so if `entry.time` is not a Date, then we just call `toString()` on it, which might be fantastically ugly (I have no idea how all of you are getting non-Dates into this field, so I don't know what to do here.  :P)  But, I also just added a feature in 2.0.0 that makes it so you can do something like:

```js
new BunyanDebugStream({
    showDate: (time, entry) => return time.toISOString()
});
```

and then you can specify whatever kind of date format you want.
